ALTER TABLE "loyalty_accounts" ALTER COLUMN "balance" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ALTER COLUMN "balance" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "aw_account_id" integer;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "program_id" text;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "provider_kind" text;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "balance_verified" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "owner_name" text;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "owner_is_connected_user" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "sync_error_code" integer;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ADD COLUMN "last_retrieved_at" timestamp;--> statement-breakpoint
-- Backfill from lib/loyalty/programs.ts (generated; the next AwardWallet sync rewrites every row anyway).
UPDATE "loyalty_accounts" SET
  "program_id" = CASE
    WHEN provider_code = 'lufthansa' THEN 'lufthansa'
    WHEN provider_code = 'klm' THEN 'flyingblue'
    WHEN provider_code = 'airfrance' THEN 'flyingblue'
    WHEN provider_code = 'skywards' THEN 'emirates'
    WHEN provider_code = 'qmiles' THEN 'qatar'
    WHEN provider_code = 'british' THEN 'british'
    WHEN provider_code = 'iberia' THEN 'iberia'
    WHEN provider_code = 'aerlingus' THEN 'aerlingus'
    WHEN provider_code = 'singaporeair' THEN 'singapore'
    WHEN provider_code = 'asia' THEN 'cathay'
    WHEN provider_code = 'aeroplan' THEN 'aeroplan'
    WHEN provider_code = 'mileageplus' THEN 'united'
    WHEN provider_code = 'delta' THEN 'delta'
    WHEN provider_code = 'jetblue' THEN 'jetblue'
    WHEN provider_code = 'aeromexico' THEN 'aeromexico'
    WHEN provider_code = 'etihad' THEN 'etihad'
    WHEN provider_code = 'eurobonus' THEN 'eurobonus'
    WHEN provider_code = 'turkish' THEN 'turkish'
    WHEN provider_code = 'thaiair' THEN 'thai'
    WHEN provider_code = 'qantas' THEN 'qantas'
    WHEN provider_code = 'virgin' THEN 'virginatlantic'
    WHEN provider_code = 'ryanair' THEN 'ryanair'
    WHEN provider_code = 'marriott' THEN 'marriott'
    WHEN provider_code = 'hhonors' THEN 'hilton'
    WHEN provider_code = 'ichotelsgroup' THEN 'ihg'
    WHEN provider_code = 'aplus' THEN 'accor'
    WHEN provider_code = 'carlson' THEN 'radisson'
    WHEN provider_code = 'choice' THEN 'choice'
    WHEN provider_code = 'solmelia' THEN 'melia'
    WHEN provider_code = 'nhhotels' THEN 'nh'
    WHEN provider_code = 'gha' THEN 'gha'
    WHEN provider_code = 'leadinghotels' THEN 'lhw'
    WHEN provider_code = 'amex' THEN 'amex-mr'
    WHEN provider_code = 'chase' THEN 'chase-ur'
    WHEN provider_code = 'capitalcards' THEN 'capital-one'
    WHEN provider_code = 'paybackgerman' THEN 'payback'
    WHEN lower(provider_name) = 'amex (membership rewards)' THEN 'amex-mr'
    WHEN lower(provider_name) = 'amex centurion' THEN 'amex-mr'
    ELSE 'aw:' || provider_code
  END,
  "balance_unit" = CASE
    WHEN provider_code = 'lufthansa' THEN 'miles'
    WHEN provider_code = 'klm' THEN 'miles'
    WHEN provider_code = 'airfrance' THEN 'miles'
    WHEN provider_code = 'skywards' THEN 'miles'
    WHEN provider_code = 'qmiles' THEN 'miles'
    WHEN provider_code = 'british' THEN 'miles'
    WHEN provider_code = 'iberia' THEN 'miles'
    WHEN provider_code = 'aerlingus' THEN 'miles'
    WHEN provider_code = 'singaporeair' THEN 'miles'
    WHEN provider_code = 'asia' THEN 'miles'
    WHEN provider_code = 'aeroplan' THEN 'miles'
    WHEN provider_code = 'mileageplus' THEN 'miles'
    WHEN provider_code = 'delta' THEN 'miles'
    WHEN provider_code = 'jetblue' THEN 'miles'
    WHEN provider_code = 'aeromexico' THEN 'miles'
    WHEN provider_code = 'etihad' THEN 'miles'
    WHEN provider_code = 'eurobonus' THEN 'miles'
    WHEN provider_code = 'turkish' THEN 'miles'
    WHEN provider_code = 'thaiair' THEN 'miles'
    WHEN provider_code = 'qantas' THEN 'miles'
    WHEN provider_code = 'virgin' THEN 'miles'
    WHEN provider_code = 'ryanair' THEN 'miles'
    WHEN provider_code = 'marriott' THEN 'points'
    WHEN provider_code = 'hhonors' THEN 'points'
    WHEN provider_code = 'ichotelsgroup' THEN 'points'
    WHEN provider_code = 'aplus' THEN 'points'
    WHEN provider_code = 'carlson' THEN 'points'
    WHEN provider_code = 'choice' THEN 'points'
    WHEN provider_code = 'solmelia' THEN 'points'
    WHEN provider_code = 'nhhotels' THEN 'points'
    WHEN provider_code = 'gha' THEN 'points'
    WHEN provider_code = 'leadinghotels' THEN 'points'
    WHEN provider_code = 'amex' THEN 'points'
    WHEN lower(provider_name) = 'amex (membership rewards)' THEN 'points'
    WHEN lower(provider_name) = 'amex centurion' THEN 'points'
    WHEN provider_code = 'chase' THEN 'points'
    WHEN provider_code = 'capitalcards' THEN 'miles'
    WHEN provider_code = 'paybackgerman' THEN 'points'
    WHEN provider_kind = 'Airlines' OR balance_unit = 'miles' THEN 'miles'
    ELSE 'points'
  END,
  "provider_name" = CASE
    WHEN provider_code = 'lufthansa' THEN 'Miles & More'
    WHEN provider_code = 'klm' THEN 'Flying Blue'
    WHEN provider_code = 'airfrance' THEN 'Flying Blue'
    WHEN provider_code = 'skywards' THEN 'Emirates Skywards'
    WHEN provider_code = 'qmiles' THEN 'Qatar Airways Privilege Club'
    WHEN provider_code = 'british' THEN 'British Airways Club'
    WHEN provider_code = 'iberia' THEN 'Iberia Plus'
    WHEN provider_code = 'aerlingus' THEN 'Aer Lingus AerClub'
    WHEN provider_code = 'singaporeair' THEN 'Singapore Airlines KrisFlyer'
    WHEN provider_code = 'asia' THEN 'Cathay'
    WHEN provider_code = 'aeroplan' THEN 'Air Canada Aeroplan'
    WHEN provider_code = 'mileageplus' THEN 'United MileagePlus'
    WHEN provider_code = 'delta' THEN 'Delta SkyMiles'
    WHEN provider_code = 'jetblue' THEN 'JetBlue TrueBlue'
    WHEN provider_code = 'aeromexico' THEN 'Aeromexico Rewards'
    WHEN provider_code = 'etihad' THEN 'Etihad Guest'
    WHEN provider_code = 'eurobonus' THEN 'SAS EuroBonus'
    WHEN provider_code = 'turkish' THEN 'Turkish Airlines Miles&Smiles'
    WHEN provider_code = 'thaiair' THEN 'Thai Airways Royal Orchid Plus'
    WHEN provider_code = 'qantas' THEN 'Qantas Frequent Flyer'
    WHEN provider_code = 'virgin' THEN 'Virgin Atlantic Flying Club'
    WHEN provider_code = 'ryanair' THEN 'Ryanair'
    WHEN provider_code = 'marriott' THEN 'Marriott Bonvoy'
    WHEN provider_code = 'hhonors' THEN 'Hilton Honors'
    WHEN provider_code = 'ichotelsgroup' THEN 'IHG One Rewards'
    WHEN provider_code = 'aplus' THEN 'Accor ALL'
    WHEN provider_code = 'carlson' THEN 'Radisson Rewards'
    WHEN provider_code = 'choice' THEN 'Choice Privileges'
    WHEN provider_code = 'solmelia' THEN 'MeliáRewards'
    WHEN provider_code = 'nhhotels' THEN 'NH DISCOVERY'
    WHEN provider_code = 'gha' THEN 'GHA DISCOVERY'
    WHEN provider_code = 'leadinghotels' THEN 'LHW Leaders Club'
    WHEN provider_code = 'amex' THEN 'Amex Membership Rewards'
    WHEN lower(provider_name) = 'amex (membership rewards)' THEN 'Amex Membership Rewards'
    WHEN lower(provider_name) = 'amex centurion' THEN 'Amex Membership Rewards'
    WHEN provider_code = 'chase' THEN 'Chase Ultimate Rewards'
    WHEN provider_code = 'capitalcards' THEN 'Capital One Miles'
    WHEN provider_code = 'paybackgerman' THEN 'PAYBACK'
    ELSE replace(provider_name, '&amp;', '&')
  END;--> statement-breakpoint
ALTER TABLE "loyalty_accounts" ALTER COLUMN "program_id" SET NOT NULL;
