/**
 * American Express Membership Rewards US transfer partners.
 *
 * SEPARATE from Amex DACH — different partner list and ratios.
 * Sources: americanexpress.com/mrupdates (official), AwardWallet, hotelredemptions.com (Apr 2026).
 *
 * Min 1,000, increments 1,000. Most airline transfers instant or up to 24 hrs; hotels 1-2 days.
 *
 * Notable 2024-2026 changes:
 * - Cathay 1:1 -> 5:4 on 01.03.2026
 * - Etihad Guest exits 30.06.2026
 *
 * Last updated: April 2026
 */

import type { PartnerMap } from './types';

const INSTANT = { de: 'sofort', en: 'instant' } as const;
const ONE_TO_TWO_DAYS = { de: '1-2 Werktage', en: '1-2 business days' } as const;
const UP_TO_THREE_DAYS = { de: 'bis zu 3 Werktage', en: 'up to 3 business days' } as const;
const UP_TO_SEVEN_DAYS = { de: 'bis zu 7 Werktage', en: 'up to 7 business days' } as const;

export const AMEX_US_PARTNERS: PartnerMap = {
  deltaSkyMiles: {
    name: 'Delta SkyMiles',
    brand: 'Delta Air Lines',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Einziger US Legacy Carrier auf Amex.',
      en: 'Only US legacy carrier on Amex.',
    },
  },
  airCanadaAeroplan: {
    name: 'Air Canada Aeroplan',
    brand: 'Air Canada',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Starker Sweet Spot.',
      en: 'Strong sweet spot.',
    },
  },
  anaMileageClub: {
    name: 'ANA Mileage Club',
    brand: 'ANA',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_THREE_DAYS,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Nur Round-Trip; sehr starke First-Class-Chart.',
      en: 'Round-trip only; killer First Class chart.',
    },
  },
  singaporeKrisflyer: {
    name: 'Singapore KrisFlyer',
    brand: 'Singapore',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  aviancaLifeMiles: {
    name: 'Avianca LifeMiles',
    brand: 'Avianca',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Häufige Transfer-Boni.',
      en: 'Frequent transfer bonuses.',
    },
  },
  britishAirways: {
    name: 'British Airways Executive Club',
    brand: 'British Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  iberia: {
    name: 'Iberia Plus',
    brand: 'Iberia',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  cathay: {
    name: 'Cathay Pacific Asia Miles',
    brand: 'Cathay Pacific',
    amexPoints: 5,
    partnerMiles: 4,
    effectiveRate: 80,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Abgewertet am 01.03.2026 von 1:1 auf 5:4.',
      en: 'Devalued on 01.03.2026 from 1:1 to 5:4.',
    },
  },
  qantas: {
    name: 'Qantas Frequent Flyer',
    brand: 'Qantas',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  qatarPrivilegeClub: {
    name: 'Qatar Privilege Club',
    brand: 'Qatar Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
    notes: {
      de: 'Avios. Qsuites Sweet Spot.',
      en: 'Avios; Qsuites sweet spot.',
    },
  },
  flyingBlue: {
    name: 'Air France-KLM Flying Blue',
    brand: 'Air France / KLM',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Monatliche Promo Rewards.',
      en: 'Monthly Promo Rewards.',
    },
  },
  aeromexico: {
    name: 'Aeromexico Club Premier',
    brand: 'Aeromexico',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_SEVEN_DAYS,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  virginAtlantic: {
    name: 'Virgin Atlantic Flying Club',
    brand: 'Virgin Atlantic',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'ANA First Class via Virgin.',
      en: 'ANA First via Virgin.',
    },
  },
  emiratesSkywards: {
    name: 'Emirates Skywards',
    brand: 'Emirates',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  etihadGuest: {
    name: 'Etihad Guest',
    brand: 'Etihad',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'PARTNERSCHAFT ENDET 30.06.2026.',
      en: 'PARTNERSHIP ENDS 30.06.2026.',
    },
  },
  hawaiianAirlines: {
    name: 'Hawaiian Airlines',
    brand: 'Hawaiian',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: '[UNVERIFIED] Atmos-Migration unklar (Stand April 2026).',
      en: '[UNVERIFIED] Atmos migration status unclear as of April 2026.',
    },
  },
  jetblueTrueBlue: {
    name: 'JetBlue TrueBlue',
    brand: 'JetBlue',
    amexPoints: 5,
    partnerMiles: 4,
    effectiveRate: 80,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Schwächste Amex-Airline-Ratio.',
      en: 'Worst Amex airline ratio.',
    },
  },
  hilton: {
    name: 'Hilton Honors',
    brand: 'Hilton',
    amexPoints: 1,
    partnerMiles: 2,
    effectiveRate: 200,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Beste Amex-Hotel-Partner-Ratio.',
      en: 'Best Amex hotel partner by ratio.',
    },
  },
  marriott: {
    name: 'Marriott Bonvoy',
    brand: 'Marriott',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Historisch 5K Bonus pro 60K transferiert.',
      en: 'Historical 5K bonus per 60K transferred.',
    },
  },
  choicePrivileges: {
    name: 'Choice Privileges',
    brand: 'Choice',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
};
