/**
 * Bilt Rewards transfer partners (US).
 *
 * Sources: support.biltrewards.com (official, last updated 25.03.2026), NerdWallet,
 * Upgraded Points (Apr 2026).
 *
 * Min 2,000 (Blue tier) / 1,000 (Silver/Gold/Platinum), increments 1,000.
 * Almost all 1:1 except Accor (3:2). Frequent Rent Day (1st of each month) transfer bonuses.
 *
 * Last updated: April 2026
 */

import type { PartnerMap } from './types';

const INSTANT = { de: 'sofort', en: 'instant' } as const;
const UP_TO_TWO_DAYS = { de: 'bis zu 2 Werktage', en: 'up to 2 business days' } as const;
const UP_TO_SEVEN_DAYS = { de: 'bis zu 7 Werktage', en: 'up to 7 business days' } as const;

export const BILT_PARTNERS: PartnerMap = {
  unitedMileagePlus: {
    name: 'United MileagePlus',
    brand: 'United',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Bilt-exklusiv unter Nicht-Chase-Programmen.',
      en: 'Bilt-exclusive among non-Chase programs.',
    },
  },
  airCanadaAeroplan: {
    name: 'Air Canada Aeroplan',
    brand: 'Air Canada',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  aviancaLifeMiles: {
    name: 'Avianca LifeMiles',
    brand: 'Avianca',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  turkishMilesSmiles: {
    name: 'Turkish Miles&Smiles',
    brand: 'Turkish',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'US-Hawaii 7.500 Meilen Sweet Spot (historisch).',
      en: 'US-Hawaii 7,500 miles sweet spot (historical).',
    },
  },
  tapMilesAndGo: {
    name: 'TAP Miles&Go',
    brand: 'TAP Portugal',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  atmos: {
    name: 'Atmos Rewards (Alaska + Hawaiian)',
    brand: 'Alaska / Hawaiian',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Bilt-exklusiv 1:1 zu Alaska; Atmos-Programm vereinheitlicht.',
      en: 'Bilt-exclusive 1:1 to Alaska; merged Atmos program.',
    },
  },
  britishAirways: {
    name: 'British Airways Executive Club',
    brand: 'British Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  iberia: {
    name: 'Iberia Plus',
    brand: 'Iberia',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  aerLingus: {
    name: 'Aer Lingus AerClub',
    brand: 'Aer Lingus',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  cathay: {
    name: 'Cathay Pacific Asia Miles',
    brand: 'Cathay Pacific',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Bilt hat Amex-Abwertung März 2026 NICHT mitgemacht — bleibt 1:1.',
      en: 'Bilt did NOT match Amex Mar 2026 devaluation; remains 1:1.',
    },
  },
  qatarPrivilegeClub: {
    name: 'Qatar Privilege Club',
    brand: 'Qatar Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  jal: {
    name: 'Japan Airlines Mileage Bank',
    brand: 'JAL',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_SEVEN_DAYS,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Bilt-exklusiv 1:1 (Capital One/Amex sind 4:3 oder schlechter).',
      en: 'Bilt-exclusive 1:1 (Capital One/Amex are 4:3 or worse).',
    },
  },
  flyingBlue: {
    name: 'Air France-KLM Flying Blue',
    brand: 'Air France / KLM',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  virginAtlantic: {
    name: 'Virgin Atlantic Flying Club',
    brand: 'Virgin Atlantic',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  virginRed: {
    name: 'Virgin Red',
    brand: 'Virgin',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  emiratesSkywards: {
    name: 'Emirates Skywards',
    brand: 'Emirates',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Bilt-exklusiv 1:1 unter Major-Programmen.',
      en: 'Bilt-exclusive 1:1 among major programs.',
    },
  },
  etihadGuest: {
    name: 'Etihad Guest',
    brand: 'Etihad',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  southwestRapidRewards: {
    name: 'Southwest Rapid Rewards',
    brand: 'Southwest',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Bilt-exklusiv (Chase ist einziger anderer Weg).',
      en: 'Bilt-exclusive (Chase only other path).',
    },
  },
  spiritFreeSpirit: {
    name: 'Spirit Free Spirit',
    brand: 'Spirit',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  hyatt: {
    name: 'World of Hyatt',
    brand: 'Hyatt',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Bilt + Chase einzige Wege; Top Hotel-Partner.',
      en: 'Bilt + Chase only paths; top hotel partner.',
    },
  },
  marriott: {
    name: 'Marriott Bonvoy',
    brand: 'Marriott',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Historisch 5K Bonus pro 20K transferiert.',
      en: 'Historical 5K bonus per 20K transferred.',
    },
  },
  hilton: {
    name: 'Hilton Honors',
    brand: 'Hilton',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Hinweis: 1:1, nicht 1:2 wie bei Amex US.',
      en: 'Note: 1:1, not Amex US 1:2.',
    },
  },
  ihg: {
    name: 'IHG One Rewards',
    brand: 'IHG',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  wyndham: {
    name: 'Wyndham Rewards',
    brand: 'Wyndham',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  accor: {
    name: 'Accor Live Limitless',
    brand: 'Accor',
    amexPoints: 3,
    partnerMiles: 2,
    effectiveRate: 66.7,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Einziger Nicht-1:1-Bilt-Partner. Häufige Rent Day Boni (bis zu 125%).',
      en: 'Only non-1:1 Bilt partner; frequent Rent Day bonuses (up to 125%).',
    },
  },
};
