/**
 * Chase Ultimate Rewards transfer partners (US).
 *
 * Sources: chase.com transfer-partners portal, Frequent Miler, Upgraded Points (Apr 2026).
 * All partners 1:1, min 1,000, increments 1,000. Only Sapphire Preferred,
 * Sapphire Reserve, and Ink Business Preferred can transfer. No transfer fees.
 *
 * Last updated: April 2026
 */

import type { PartnerMap } from './types';

const INSTANT = { de: 'sofort', en: 'instant' } as const;
const ONE_TO_TWO_DAYS = { de: '1-2 Werktage', en: '1-2 business days' } as const;

export const CHASE_PARTNERS: PartnerMap = {
  unitedMileagePlus: {
    name: 'United MileagePlus',
    brand: 'United',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Excursionist Perk. Close-in-Gebühren für Premier-Member entfallen.',
      en: 'Excursionist Perk; close-in fees waived for Premier members.',
    },
  },
  airCanadaAeroplan: {
    name: 'Air Canada Aeroplan',
    brand: 'Air Canada',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Starke Star-Alliance-Award-Chart, Stopovers erlaubt.',
      en: 'Strong Star Alliance award chart, stopovers allowed.',
    },
  },
  singaporeKrisflyer: {
    name: 'Singapore KrisFlyer',
    brand: 'Singapore Airlines',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Bester Zugang zu Singapore Suites/First Class.',
      en: 'Best access to Singapore Suites/First Class.',
    },
  },
  southwestRapidRewards: {
    name: 'Southwest Rapid Rewards',
    brand: 'Southwest',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Companion Pass berechtigt.',
      en: 'Companion Pass eligible.',
    },
  },
  jetblueTrueBlue: {
    name: 'JetBlue TrueBlue',
    brand: 'JetBlue',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Revenue-basiert; ~1.3 Cent pro Punkt.',
      en: 'Revenue-based; ~1.3 cpp.',
    },
  },
  britishAirways: {
    name: 'British Airways Executive Club',
    brand: 'British Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
    notes: {
      de: 'Avios. Sweet Spots auf Kurzstrecken.',
      en: 'Avios; short-haul sweet spots.',
    },
  },
  iberia: {
    name: 'Iberia Plus',
    brand: 'Iberia',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
    notes: {
      de: 'Avios. Off-Peak transatlantische Deals.',
      en: 'Avios; off-peak transatlantic deals.',
    },
  },
  aerLingus: {
    name: 'Aer Lingus AerClub',
    brand: 'Aer Lingus',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
    notes: {
      de: 'Avios. US-Europa Sweet Spots.',
      en: 'Avios; US-Europe sweet spots.',
    },
  },
  flyingBlue: {
    name: 'Air France-KLM Flying Blue',
    brand: 'Air France / KLM',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Monatliche Promo Rewards (oft 50% Rabatt).',
      en: 'Monthly Promo Rewards (often 50% off).',
    },
  },
  virginAtlantic: {
    name: 'Virgin Atlantic Flying Club',
    brand: 'Virgin Atlantic',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'ANA First/Business via Virgin Sweet Spot.',
      en: 'ANA First/Business via Virgin sweet spot.',
    },
  },
  hyatt: {
    name: 'World of Hyatt',
    brand: 'Hyatt',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Bester Hotel-Partner aller Programme. Award-Chart fest.',
      en: 'Best hotel partner in any program; published award chart.',
    },
  },
  marriott: {
    name: 'Marriott Bonvoy',
    brand: 'Marriott',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Generell schwacher Wert.',
      en: 'Generally poor value.',
    },
  },
  ihg: {
    name: 'IHG One Rewards',
    brand: 'IHG',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Generell schwacher Wert.',
      en: 'Generally poor value.',
    },
  },
};
