/**
 * Citi ThankYou Points transfer partners (US).
 *
 * Sources: thepointsguy.com (Aug 2025), frequentmiler.com (19.02.2026),
 * onemileatatime.com, thriftytraveler.com (14.04.2026).
 *
 * Min 1,000, increments 1,000.
 *
 * CRITICAL: Ratios below are for premium cards (Strata Premier, Strata Elite, Prestige).
 * Cards earning "limited" ThankYou points (Custom Cash, Rewards+) get reduced ratios on
 * some partners.
 *
 * Notable 2024-2026 changes:
 * - Choice Privileges devalued 19.04.2026 from 1:2 to 1:1.5 (-25%)
 * - I Prefer devalued 19.04.2026 from 1:4 to 1:2 (-50%)
 *
 * Last updated: April 2026
 */

import type { PartnerMap } from './types';

const INSTANT = { de: 'sofort', en: 'instant' } as const;
const UP_TO_TWO_DAYS = { de: 'bis zu 2 Werktage', en: 'up to 2 business days' } as const;
const UP_TO_FIVE_DAYS = { de: 'bis zu 5 Werktage', en: 'up to 5 business days' } as const;
const UP_TO_FOURTEEN_DAYS = { de: 'bis zu 14 Werktage', en: 'up to 14 business days' } as const;

export const CITI_PARTNERS: PartnerMap = {
  americanAirlines: {
    name: 'American Airlines AAdvantage',
    brand: 'American',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Citi-exklusiv 1:1 zu AA unter Major-Issuern.',
      en: 'Citi-exclusive 1:1 to AA among major issuers.',
    },
  },
  cathay: {
    name: 'Cathay Pacific Asia Miles',
    brand: 'Cathay Pacific',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  qantas: {
    name: 'Qantas Frequent Flyer',
    brand: 'Qantas',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  qatarPrivilegeClub: {
    name: 'Qatar Privilege Club',
    brand: 'Qatar Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  evaInfinityMileageLands: {
    name: 'EVA Air Infinity MileageLands',
    brand: 'EVA',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_FOURTEEN_DAYS,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Besser als Capital Ones 4:3.',
      en: "Better than Capital One's 4:3.",
    },
  },
  aviancaLifeMiles: {
    name: 'Avianca LifeMiles',
    brand: 'Avianca',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  singaporeKrisflyer: {
    name: 'Singapore KrisFlyer',
    brand: 'Singapore',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: { de: '1-2 Werktage', en: '1-2 business days' },
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  thaiRoyalOrchid: {
    name: 'Thai Royal Orchid Plus',
    brand: 'Thai',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_FOURTEEN_DAYS,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Citi-exklusiv unter US-Major.',
      en: 'Citi-exclusive among major US.',
    },
  },
  turkishMilesSmiles: {
    name: 'Turkish Miles&Smiles',
    brand: 'Turkish',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  flyingBlue: {
    name: 'Air France-KLM Flying Blue',
    brand: 'Air France / KLM',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  aeromexico: {
    name: 'Aeromexico Club Premier',
    brand: 'Aeromexico',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  etihadGuest: {
    name: 'Etihad Guest',
    brand: 'Etihad',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  emiratesSkywards: {
    name: 'Emirates Skywards',
    brand: 'Emirates',
    amexPoints: 5,
    partnerMiles: 4,
    effectiveRate: 80,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: '1.000 Citi = 800 Emirates.',
      en: '1,000 Citi = 800 Emirates.',
    },
  },
  jetblueTrueBlue: {
    name: 'JetBlue TrueBlue',
    brand: 'JetBlue',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: '5:4 für Limited-Earning Cards.',
      en: '5:4 for limited-earning cards.',
    },
  },
  virginAtlantic: {
    name: 'Virgin Atlantic Flying Club',
    brand: 'Virgin Atlantic',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  wyndham: {
    name: 'Wyndham Rewards',
    brand: 'Wyndham',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_FIVE_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Bonus alle ~6 Monate (25% live bis 21.03.2026).',
      en: 'Bonuses ~every 6 months (25% live through 21.03.2026).',
    },
  },
  choicePrivileges: {
    name: 'Choice Privileges',
    brand: 'Choice',
    amexPoints: 2,
    partnerMiles: 3,
    effectiveRate: 150,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Abgewertet 19.04.2026 von 1:2 auf 1:1,5 (-25%).',
      en: 'Devalued 19.04.2026 from 1:2 to 1:1.5 (-25%).',
    },
  },
  accor: {
    name: 'Accor Live Limitless',
    brand: 'Accor',
    amexPoints: 2,
    partnerMiles: 1,
    effectiveRate: 50,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: '1.000 Citi = 500 Accor.',
      en: '1,000 Citi = 500 Accor.',
    },
  },
  iPrefer: {
    name: 'I Prefer Hotel Rewards',
    brand: 'Preferred',
    amexPoints: 1,
    partnerMiles: 2,
    effectiveRate: 200,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Abgewertet 19.04.2026 von 1:4 auf 1:2 (-50%).',
      en: 'Devalued 19.04.2026 from 1:4 to 1:2 (-50%).',
    },
  },
  leadingHotels: {
    name: 'Leading Hotels of the World Leaders Club',
    brand: 'LHW',
    amexPoints: 5,
    partnerMiles: 1,
    effectiveRate: 20,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: '1.000 Citi = 200 LHW.',
      en: '1,000 Citi = 200 LHW.',
    },
  },
  virginRed: {
    name: 'Virgin Red',
    brand: 'Virgin',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    type: 'other',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Retail/Erlebnis-Programm.',
      en: 'Retail/experiences program.',
    },
  },
};
