/**
 * Capital One Venture transfer partners (US).
 *
 * Sources: capitalone.com/credit-cards/travel-partners (official, 29.01.2026 update),
 * The Points Guy (13.02.2026), AwardWallet, Going.
 *
 * Min 1,000, increments 1,000.
 *
 * Important: Capital One does NOT include United, Delta, American, Southwest,
 * JetBlue, or Hyatt.
 *
 * Last updated: April 2026
 */

import type { PartnerMap } from './types';

const INSTANT = { de: 'sofort', en: 'instant' } as const;
const ONE_TO_TWO_DAYS = { de: '1-2 Werktage', en: '1-2 business days' } as const;
const UP_TO_24_HRS = { de: 'bis zu 24 Stunden', en: 'up to 24 hours' } as const;
const UP_TO_36_HRS = { de: 'bis zu 36 Stunden', en: 'up to 36 hours' } as const;

export const CAPITAL_ONE_PARTNERS: PartnerMap = {
  airCanadaAeroplan: {
    name: 'Air Canada Aeroplan',
    brand: 'Air Canada',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  aviancaLifeMiles: {
    name: 'Avianca LifeMiles',
    brand: 'Avianca',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  turkishMilesSmiles: {
    name: 'Turkish Miles&Smiles',
    brand: 'Turkish',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  tapMilesAndGo: {
    name: 'TAP Air Portugal Miles&Go',
    brand: 'TAP',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  singaporeKrisflyer: {
    name: 'Singapore KrisFlyer',
    brand: 'Singapore',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  evaInfinityMileageLands: {
    name: 'EVA Air Infinity MileageLands',
    brand: 'EVA',
    amexPoints: 4,
    partnerMiles: 3,
    effectiveRate: 75,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_36_HRS,
    alliance: 'Star Alliance',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: '1.000 C1 = 750 EVA.',
      en: '1,000 C1 = 750 EVA.',
    },
  },
  britishAirways: {
    name: 'British Airways Executive Club',
    brand: 'British Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  cathay: {
    name: 'Cathay Pacific Asia Miles',
    brand: 'Cathay Pacific',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_24_HRS,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: 'Capital One hat NICHT abgewertet — bleibt 1:1.',
      en: 'Capital One did NOT devalue (still 1:1).',
    },
  },
  finnair: {
    name: 'Finnair Plus',
    brand: 'Finnair',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  qantas: {
    name: 'Qantas Frequent Flyer',
    brand: 'Qantas',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  qatarPrivilegeClub: {
    name: 'Qatar Privilege Club',
    brand: 'Qatar Airways',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Avios', en: 'Avios' },
  },
  jal: {
    name: 'Japan Airlines Mileage Bank',
    brand: 'JAL',
    amexPoints: 4,
    partnerMiles: 3,
    effectiveRate: 75,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'Oneworld',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
    notes: {
      de: '30%-Bonus bis 30.04.2026 (effektiv ~1000:975).',
      en: 'LIVE 30% bonus through 30.04.2026 (effective ~1000:975).',
    },
  },
  flyingBlue: {
    name: 'Air France-KLM Flying Blue',
    brand: 'Air France / KLM',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  aeromexico: {
    name: 'Aeromexico Club Premier',
    brand: 'Aeromexico',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: 'SkyTeam',
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  emiratesSkywards: {
    name: 'Emirates Skywards',
    brand: 'Emirates',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  etihadGuest: {
    name: 'Etihad Guest',
    brand: 'Etihad',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Meilen', en: 'Miles' },
  },
  virginRed: {
    name: 'Virgin Red',
    brand: 'Virgin',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    alliance: null,
    type: 'airline',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Virgin-Atlantic-Zugang via Virgin Red.',
      en: 'Includes Virgin Atlantic access via Virgin Red.',
    },
  },
  wyndham: {
    name: 'Wyndham Rewards',
    brand: 'Wyndham',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
  },
  choicePrivileges: {
    name: 'Choice Privileges',
    brand: 'Choice',
    amexPoints: 1,
    partnerMiles: 1,
    effectiveRate: 100,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: UP_TO_24_HRS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Nur US-Konten.',
      en: 'US accounts only.',
    },
  },
  accor: {
    name: 'Accor Live Limitless',
    brand: 'Accor',
    amexPoints: 2,
    partnerMiles: 1,
    effectiveRate: 50,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: ONE_TO_TWO_DAYS,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: '1.000 C1 = 500 Accor; schwacher Wert.',
      en: '1,000 C1 = 500 Accor; weak.',
    },
  },
  iPrefer: {
    name: 'I Prefer (Preferred Hotels)',
    brand: 'Preferred',
    amexPoints: 1,
    partnerMiles: 2,
    effectiveRate: 200,
    minTransfer: 1000,
    transferIncrement: 1000,
    transferDuration: INSTANT,
    type: 'hotel',
    currencyUnit: { de: 'Punkte', en: 'Points' },
    notes: {
      de: 'Beste Capital-One-Hotel-Ratio.',
      en: 'Best Capital One hotel ratio.',
    },
  },
};
